In [1]:
import numpy as np

In [4]:
# 1-D array
a = [1,2,3,4,5]

arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [7]:
# To check dimenion of array

arr.ndim

1

In [13]:
# alternate way to write 1-D array/direct array
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

print(arr1.ndim)

[1 2 3 4 5 6 7]
1


In [14]:
arr.dtype

dtype('int64')

In [17]:
# Shape of Array

arr.shape

# it's 1d array that's why it is showing only row(it start at 1 and end at 7)

(5,)

In [18]:
# Size of Array

arr.size

5

In [20]:
# Two Dimensional array
# first we create a list and then list inside list as child list

b = [[1,2,3],[4,5,6]]
arr2 = np.array(b)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2.ndim

2

In [23]:
# Alternate way to write 2d array

arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# (2, 3) -> 2 for row and 3 for column
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

(2, 3)
6
int64


In [27]:
# Another way to create array using arange function it is more effiecent then range function
# arange(start point, ending point,step) --> so if we don't give step bydefault it's 1 and ending point is excluded 
# -> like arange from 1,15 it only write till 14

arr4 = np.arange(1,15)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr4 = np.arange(1,19,3)
arr4

array([ 1,  4,  7, 10, 13, 16])

In [30]:
# To write odd and even through arange

arr5 = np.arange(2,19,2) # To write even numbers
arr6 = np.arange(1,20,3) # To write odd numbers
print(arr5)
print(arr6)

[ 2  4  6  8 10 12 14 16 18]
[ 1  4  7 10 13 16 19]


# Numpy Functions

In [33]:
# create 1d array
arr = np.zeros(8)
print(arr)
print(arr.ndim)

[0. 0. 0. 0. 0. 0. 0. 0.]
1


In [34]:
# create 2d array
# arr = np.zeros([rows,columns])
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr1 = np.ones(8)
print(arr1)
print(arr1.ndim)

[1. 1. 1. 1. 1. 1. 1. 1.]
1


In [36]:
arr1 = np.ones([5,12])
print(arr1)
print(arr1.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
2


In [37]:
# np.eye function is used to write array 1 diagonally(diagonally once[1] has been printed & rest of the elements are zero)
# when we use the function diagonally it gives one, so if i change it's from 4 to 3. so 3 ones diagonally printed and rest element zero.

arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
arr2 = np.eye(5) # 5 row and 5 column
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr2 = np.eye(4,6) # to write the rectangle array 4 row , 6 column
arr2

# they are not in diagonal shpae this is the only drawback in it

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [43]:
# diag stands for diagonal and the number print diagonally and rest of element are zeros
arr = np.diag([4,5,6,7,8,9])
arr

array([[4, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 9]])

In [45]:
arr = np.diag([4,5,6])
arr

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [48]:
# To print random integers
# np.random.randint(minimum[means where to start], maximum[where to end],total no of values)

arr = np.random.randint(1,10,6)
arr
arr

array([2, 7, 5, 5, 7, 8])

In [51]:
# random.rand takes only one value and those value range from 0 to 1.
arr = np.random.rand(5)
print(arr)
print(arr.ndim)

[0.98115149 0.71734516 0.31530169 0.17250861 0.2647624 ]
1


In [54]:
# To change random.rand into 2d array
arr = np.random.rand(3,4)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[0.39251175 0.65427798 0.31405494 0.27904705]
 [0.30126194 0.36846688 0.55129329 0.5195408 ]
 [0.83036204 0.85372494 0.92732911 0.39674256]]
2
(3, 4)
12
float64


In [56]:
# random.randn only take 1 value
# This function gives the nearest to the zero value means the number can be -ve or can be +ve but the
# numbers will be nearest to the zero

arr = np.random.randn(8)
arr

array([-0.86027709,  0.55480476,  0.84653054, -1.28780377,  0.28466022,
       -2.26581692, -0.79193115,  0.20789738])

In [58]:
#linspace take 3 parameters
# linspace(start,end,how many elements we want)

lspace = np.linspace(1,5,4)
lspace

# These functions separate these four elements in such a way that the ring that the difference between the 2 elements will be always same
# means the difference between this 2.3 and 1 is same as the difference from 2.3 to 3.6 is also same and the differnce from 3.6 to 5 is
# also same, so this function separates the differences in equal way.

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [59]:
lspace = np.linspace(1,10,10)
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# RESHAPE

In [65]:
# random.randint(start,end,total elemet)

arr = np.random.randint(1,50,12)
print(arr)
print(arr.ndim)
print(arr.size)

# changing 1d array to 2d array
arr1 = arr.reshape(2,6) # 2 rows and 6 column
print(arr1)
print(arr1.ndim)

# changing 2d array in 1d array
arr2 = arr1.reshape(12)
print(arr2)
print(arr2.ndim)

# reshape array -> we can convert array in such a way that the multiplication of the given rows and columns means here if it is 6 then
# the multiplication of 2 & 6 will 12 so this 12 should match with this number of element present in 1D array.

#  we can only give this two values here the value of rows and columns. so, that the multiplication of this two values should be equal to
# the number of elements present in our 1D array.

[44 37 44 13 30  1 38 14 22 39 40 41]
1
12
[[44 37 44 13 30  1]
 [38 14 22 39 40 41]]
2
[44 37 44 13 30  1 38 14 22 39 40 41]
1


In [69]:
arr = np.random.randint(1,50,10)
arr1 = arr.reshape(2,-1)
print(arr1)
print('\n')
arr2 = arr.reshape(-1,2)
print(arr2)
# array reshape function can take column or the row by itself.

[[41 47 47 11 27]
 [36 18  1 11 13]]


[[41 47]
 [47 11]
 [27 36]
 [18  1]
 [11 13]]


Seed Function:-> seed function is that whenever we want to print the rand arrays of random integers.so, what happens
each time when we execute the code it genrate different codes

Seed:-> suppose if we want to generate codes randomly but fixed numbers of elements, so that the elements should be fixed
so that if i run my program in one pc so the numbers which are occuring randomly should be same if i'll run the same code in another PC also.

arr = np.random.randint(1,50,10) => basically this function does that it saves your elements on this number on the number we are given here in this function

In [73]:
np.random.seed(12)
arr = np.random.randint(1,50,10)
arr

array([12, 28,  7,  3,  4,  4, 13, 49, 23,  6])

# Create 1D Array From Taking Input From The User

In [75]:
a = []   # creating a empty variable
size = int(input("Enter the Size : ")) # Take the total size of the elements
for i in range(size):       # we say for i in range size do what
    val = int(input("Enter a number : ")) # Take the imput of the values it will also taken in integer format
    a.append(val)                         # Append these values into our list that is a.

arr = np.array(a)  # converting list into array
arr
    

Enter the Size :  6
Enter a number :  7
Enter a number :  3
Enter a number :  4
Enter a number :  5
Enter a number :  6
Enter a number :  7


array([7, 3, 4, 5, 6, 7])

# 2D Array By Taking User Input

In [79]:
matrix = [] #list with name matrix called 2d array
row = int(input("Enter the number of rows : "))
col = int(input("Enter the number of cols : "))
for i in range(row):
    a = []
    for i in range(col):
        val = int(input("Enter a number : "))
        a.append(val)
    matrix.append(a)
arr = np.array(matrix)
arr

Enter the number of rows :  1
Enter the number of cols :  2
Enter a number :  1
Enter a number :  2


array([[1, 2]])

# Slicing, View & Copy, Conditional Selection, Operations On Numpy Arrays

# Slicing

In [80]:
np.random.seed(111)
arr = np.random.randint(1,500,30).reshape(6,5)
arr

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [81]:
#  arr(oth->index:nth index[row], [column] oth index:nth index)
arr[:4,:]

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285]])

In [82]:
arr[2:4,1:4]

array([[456, 442,   8],
       [450, 369, 217]])

<h2>View and Copy</h2>

In [83]:
a = np.arange(1,16)
view = a[:].view()
print(view)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [87]:
a = np.arange(1,16)
view = a[:].view()
view[3:6] = 0  # Here,this will do change 3rd element to 5th element turn to zero
print(view)
print(a)

# This changes we make to view array are also reflect/performed to main array

[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]
[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]


In [88]:
a = np.arange(1,16)
copy = a[:].copy()
copy[3:6] = 0
print(copy)
print(a)

# The changes we make to copy array are not performed to main array

[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# Conditional Selection

In [89]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
# Conditional Selection -> like we can select the elements of our present in our array by giving condition to them.

In [94]:
a > 10  

#It is giving false for all the values that are less then 10 and true for greater then 10 this is conditional slection.

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [97]:
a[a > 10]

# first we print array then in square bracket we put condition and run the code it will give only condition desired result.


array([11, 12, 13, 14, 15])

In [99]:
a = np.arange(1,16)
print(a)
a[a%2==0] # For Even Number

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 2,  4,  6,  8, 10, 12, 14])

In [101]:
a[a%2!=0] # For Odd Number

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# Mathematical Operations 

In [102]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [104]:
arr+2 # 2 add to every elemet

array([3, 4, 5, 6])

In [105]:
arr*7

array([ 7, 14, 21, 28])

In [107]:
arr**3  # Cube of every element

array([ 1,  8, 27, 64])

In [112]:
arr1 = np.arange(1,8)
arr2 = np.arange(3,10)
print(arr1)
print(arr2)

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]


In [113]:
arr1 + arr2

array([ 4,  6,  8, 10, 12, 14, 16])

In [114]:
arr1 = np.arange(1, 5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [115]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [116]:
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

In [117]:
arr1 / arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [118]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [119]:
# To Perform original multiplication matrix's

arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

# More Functions And Stacking On Numpy Arrays

# Function Of Numpy Arrays

In [121]:
arr = np.array([12,3,4,61,9,10])
np.min(arr)

np.int64(3)

In [123]:
np.max(arr) # maximum value in array

np.int64(61)

In [124]:
# Now, we can find the index at which the minimum element or maximum element has been present using the argmin

np.argmin(arr)

np.int64(1)

In [125]:
np.argmax(arr)

np.int64(3)

In [126]:
np.sqrt(arr)

array([3.46410162, 1.73205081, 2.        , 7.81024968, 3.        ,
       3.16227766])

In [127]:
np.sin(arr) #sin value 

array([-0.53657292,  0.14112001, -0.7568025 , -0.96611777,  0.41211849,
       -0.54402111])

In [128]:
np.cos(arr) #cos value

array([ 0.84385396, -0.9899925 , -0.65364362, -0.25810164, -0.91113026,
       -0.83907153])

In [129]:
np.random.seed(111) # we use random.seed function so number cannot change each time.
matrix = np.random.randint(1,21,9).reshape(3,3)
matrix

array([[13, 20, 10],
       [ 3, 19,  9],
       [ 8,  8, 13]])

In [130]:
np.sum(matrix)

np.int64(103)

In [131]:
np.min(matrix)

np.int64(3)

In [132]:
np.max(matrix)

np.int64(20)

In [133]:
# We can check min & max value according to axes
# these row[13,20,10] this is inner row & this row in present in axis one. so, the horizontal line always belongs to axes one
# and[13]
#    [3]
#    [8] this is a column & this is the first column of my matrix or our array. so, this column is a vertical line
# so, the vertical line always belong to axes zeo(0).

In [135]:
np.min(matrix,axis = 1)  # axis=1 for row
# it will check all the columns and then write minimum value from them
# row1 - has 10 as minimum value
# row2 - has 3 as minimum value
# row3 - has 8 as minimum value

array([10,  3,  8])

In [136]:
np.min(matrix, axis = 0) # axis=0 for column

array([3, 8, 9])

In [137]:
np.max(matrix, axis=1)

array([20, 19, 13])

In [138]:
np.max(matrix, axis=0)

array([13, 20, 13])

In [139]:
np.sum(matrix, axis=1)

array([43, 31, 29])

In [140]:
np.sum(matrix, axis=0)

array([24, 47, 32])

In [141]:
# Cummulative sum

np.cumsum(matrix)

array([ 13,  33,  43,  46,  65,  74,  82,  90, 103])

In [142]:
np.cumsum(matrix,axis=1)

array([[13, 33, 43],
       [ 3, 22, 31],
       [ 8, 16, 29]])

In [143]:
np.cumsum(matrix, axis = 0)

array([[13, 20, 10],
       [16, 39, 19],
       [24, 47, 32]])

<h3> Shuffle and Unique</h3>

In [144]:
arr = np.random.randint(1,21,10)
arr

array([11,  2, 17, 15,  3,  9,  6, 13,  7, 13])

In [145]:
np.random.shuffle(arr)
arr

array([ 3,  2, 11, 13, 15, 17, 13,  6,  7,  9])

In [146]:
arr1 = np.array([10,20,30,40,10,20,30,50])
arr1

array([10, 20, 30, 40, 10, 20, 30, 50])

In [147]:
np.unique(arr1)

array([10, 20, 30, 40, 50])

In [148]:
np.unique(arr1).size

5

In [150]:
np.unique(arr1,return_index = True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 7]))

In [151]:
# np.unique(array_name,retrun index, count of elements)
np.unique(arr1,return_index = True,return_counts=True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 7]), array([2, 2, 2, 1, 1]))

# Stacking

In [152]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [153]:
np.hstack((a,b)) # horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [154]:
np.vstack((a,b)) # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
np.random.seed(111)
a1 = np.random.randint(1,21,9).reshape(3,3)
b1 = np.random.randint(21,41,9).reshape(3,3)
print(a1)
print(b1)

[[13 20 10]
 [ 3 19  9]
 [ 8  8 13]]
[[31 22 37]
 [35 23 29]
 [26 33 27]]


In [157]:
np.hstack((a1,b1))  # horizontal stacking it's just like 1d array

array([[13, 20, 10, 31, 22, 37],
       [ 3, 19,  9, 35, 23, 29],
       [ 8,  8, 13, 26, 33, 27]])

In [158]:
np.vstack((a1,b1))

array([[13, 20, 10],
       [ 3, 19,  9],
       [ 8,  8, 13],
       [31, 22, 37],
       [35, 23, 29],
       [26, 33, 27]])