In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

np.float64(180616.43835616432)

In [7]:
model.predict([[5000]])

/home/debian/.pyenv/versions/3.10.14/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

# Save Model To a File Using Python Pickle

In [8]:
import pickle

In [9]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

# Load Saved Model

wb - write binary, rb - read binary

In [10]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

np.float64(180616.43835616432)

In [13]:
mp.predict([[5000]])

/home/debian/.pyenv/versions/3.10.14/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

# Save Trained Model Using joblib

In [16]:
#!pip install --upgrade scikit-learn

If our model consists of large numoy arrays then using joblib might be more efficient

In [17]:
from joblib import dump, load

In [18]:
import joblib

In [19]:
joblib.dump(model, 'model_joblib')

['model_joblib']

# Load Saved Model

In [20]:
mj = joblib.load('model_joblib')

In [21]:
mj.coef_

array([135.78767123])

In [22]:
mj.intercept_

np.float64(180616.43835616432)

In [23]:
mj.predict([[5000]])

/home/debian/.pyenv/versions/3.10.14/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])